"use strict";

window.WEAPON_ICONS = Object.freeze({
  "ボールドマーカー": "Sploosh-o-matic.png",
  "ボールドマーカーネオ": "Neo Sploosh-o-matic.png",
  "わかばシューター": "Splattershot Jr..png",
  "もみじシューター": "Custom Splattershot Jr.png",
  "シャープマーカー": "Splash-o-matic.png",
  "シャープマーカーネオ": "Neo Splash-o-matic.png",
  "シャープマーカーGECK": "Splash-o-matic GCK-O.png",
  "プロモデラーRG": "Aerospray RG.png",
  "プロモデラーMG": "Aerospray MG.png",
  "プロモデラー彩": "Colorz Aerospray.png",
  "スプラシューター": "Splattershot.png",
  "スプラシューターコラボ": "Tentatek Splattershot.png",
  "スプラシューター煌": "Glamorz Splattershot.png",
  ".52ガロン": "52 Gal.png",
  ".52ガロンデコ": "52 Gal Deco.png",
  "N-ZAP85": "N-ZAP 85.png",
  "N-ZAP89": "N-ZAP 89.png",
  "プライムシューター": "Splattershot Pro.png",
  "プライムシューターコラボ": "Forge Splattershot Pro.png",
  "プライムシューターFRZN": "Splattershot Pro FRZ-N.png",
  ".96ガロン": "96 Gal.png",
  ".96ガロンデコ": "96 Gal Deco.png",
  ".96ガロン爪": "Clawz 96 Gal.png",
  "ジェットスイーパー": "Jet Squelcher.png",
  "ジェットスイーパーカスタム": "Custom Jet Squelcher.png",
  "ジェットスイーパーCOBR": "Jet Squelcher COB-R.png",
  "スペースシューター": "Splattershot Nova.png",
  "スペースシューターコラボ": "Annaki Splattershot Nova.png",
  "L3リールガン": "L-3 Nozzlenose.png",
  "L3リールガンD": "L-3 Nozzlenose D.png",
  "L3リールガン箔": "Glitterz L-3 Nozzlenose.png",
  "H3リールガン": "H-3 Nozzlenose.png",
  "H3リールガンD": "H-3 Nozzlenose D.png",
  "H3リールガンSNAK": "H-3 Nozzlenose VIP-R.png",
  "ボトルガイザー": "Squeezer.png",
  "ボトルガイザーフォイル": "Foil Squeezer.png",

  "カーボンローラー": "Carbon Roller.png",
  "カーボンローラーデコ": "Carbon Roller Deco.png",
  "カーボンローラーANGL": "Carbon Roller ANG-L.png",
  "スプラローラー": "Splat Roller.png",
  "スプラローラーコラボ": "Krak-On Splat Roller.png",
  "ダイナモローラー": "Dynamo Roller.png",
  "ダイナモローラーテスラ": "Gold Dynamo Roller.png",
  "ダイナモローラー冥": "Starz Dynamo Roller.png",
  "ヴァリアブルローラー": "Flingza Roller.png",
  "ヴァリアブルローラーフォイル": "Foil Flingza Roller.png",
  "ワイドローラー": "Big Swig Roller.png",
  "ワイドローラーコラボ": "Big Swig Roller Express.png",
  "ワイドローラー惑": "Planetz Big Swig Roller.png",

  "スクイックリンα": "Classic Squiffer.png",
  "スクイックリンβ": "New Squiffer.png",
  "スプラチャージャー": "Splat Charger.png",
  "スプラチャージャーコラボ": "ZF Splat Charger.png",
  "スプラチャージャーFRST": "Splat Charger CAM-O.png",
  "スプラスコープ": "Splatterscope.png",
  "スプラスコープコラボ": "ZF Splatterscope.png",
  "スプラスコープFRST": "Splatterscope CAM-O.png",
  "リッター4K": "E-liter 4K.png",
  "リッター4Kカスタム": "Custom E-liter 4K.png",
  "4Kスコープ": "E-liter 4K Scope.png",
  "4Kスコープカスタム": "Custom E-liter 4K Scope.png",
  "14式竹筒銃・甲": "Bamboozler 14 Mk I.png",
  "14式竹筒銃・乙": "Bamboozler 14 Mk II.png",
  "ソイチューバー": "Goo Tuber.png",
  "ソイチューバーカスタム": "Custom Goo Tuber.png",
  "R-PEN/5H": "Snipewriter 5H.png",
  "R-PEN/5B": "Snipewriter 5B.png",

  "ノヴァブラスター": "Luna Blaster.png",
  "ノヴァブラスターネオ": "Luna Blaster Neo.png",
  "ホットブラスター": "Blaster.png",
  "ホットブラスターカスタム": "Custom Blaster.png",
  "ホットブラスター艶": "Gleamz Blaster.png",
  "ロングブラスター": "Range Blaster.png",
  "ロングブラスターカスタム": "Custom Range Blaster.png",
  "クラッシュブラスター": "Clash Blaster.png",
  "クラッシュブラスターネオ": "Clash Blaster Neo.png",
  "ラピッドブラスター": "Rapid Blaster.png",
  "ラピッドブラスターデコ": "Rapid Blaster Deco.png",
  "Rブラスターエリート": "Rapid Blaster Pro.png",
  "Rブラスターエリートデコ": "Rapid Blaster Pro Deco.png",
  "RブラスターエリートWNTR": "Rapid Blaster Pro WNT-R.png",
  "S-BLAST92": "S-BLAST 92.png",
  "S-BLAST91": "S-BLAST 91.png",

  "バケットスロッシャー": "Slosher.png",
  "バケットスロッシャーデコ": "Slosher Deco.png",
  "ヒッセン": "Tri-Slosher.png",
  "ヒッセン・ヒュー": "Tri-Slosher Nouveau.png",
  "ヒッセンASH": "Tri-Slosher ASH-N.png",
  "スクリュースロッシャー": "Sloshing Machine.png",
  "スクリュースロッシャーネオ": "Sloshing Machine Neo.png",
  "オーバーフロッシャー": "Bloblobber.png",
  "オーバーフロッシャーデコ": "Bloblobber Deco.png",
  "エクスプロッシャー": "Explosher.png",
  "エクスプロッシャーカスタム": "Custom Explosher.png",
  "モップリン": "Dread Wringer.png",
  "モップリンD": "Dread Wringer D.png",
  "モップリン角": "Hornz Dread Wringer.png",

  "スプラスピナー": "Mini Splatling.png",
  "スプラスピナーコラボ": "Zink Mini Splatling.png",
  "スプラスピナーPYTN": "Mini Splatling RTL-R.png",
  "バレルスピナー": "Heavy Splatling.png",
  "バレルスピナーデコ": "Heavy Splatling Deco.png",
  "ハイドラント": "Hydra Splatling.png",
  "ハイドラントカスタム": "Custom Hydra Splatling.png",
  "ハイドラント圧": "Torrentz Hydra Splatling.png",
  "クーゲルシュライバー": "Ballpoint Splatling.png",
  "クーゲルシュライバー・ヒュー": "Ballpoint Splatling Nouveau.png",
  "ノーチラス47": "Nautilus 47.png",
  "ノーチラス79": "Nautilus 79.png",
  "イグザミナー": "Heavy Edit Splatling.png",
  "イグザミナー・ヒュー": "Heavy Edit Splatling Nouveau.png",

  "パブロ": "Inkbrush.png",
  "パブロ・ヒュー": "Inkbrush Nouveau.png",
  "ホクサイ": "Octobrush.png",
  "ホクサイ・ヒュー": "Octobrush Nouveau.png",
  "ホクサイ彗": "Cometz Octobrush.png",
  "フィンセント": "Painbrush.png",
  "フィンセント・ヒュー": "Painbrush Nouveau.png",
  "フィンセントBRNZ": "Painbrush BRN-Z.png",

  "スパッタリー": "Dapple Dualies.png",
  "スパッタリー・ヒュー": "Dapple Dualies Nouveau.png",
  "スパッタリーOWL": "Dapple Dualies NOC-T.png",
  "スプラマニューバー": "Splat Dualies.png",
  "スプラマニューバーコラボ": "Enperry Splat Dualies.png",
  "スプラマニューバー耀": "Twinklez Splat Dualies.png",
  "ケルビン525": "Glooga Dualies.png",
  "ケルビン525デコ": "Glooga Dualies Deco.png",
  "デュアルスイーパー": "Dualie Squelchers.png",
  "デュアルスイーパーカスタム": "Custom Dualie Squelchers.png",
  "デュアルスイーパー蹄": "Hoofz Dualie Squelchers.png",
  "クアッドホッパーブラック": "Dark Tetra Dualies.png",
  "クアッドホッパーホワイト": "Light Tetra Dualies.png",
  "ガエンFF": "Douser Dualies FF.png",
  "ガエンFFカスタム": "Custom Douser Dualies FF.png",

  "パラシェルター": "Splat Brella.png",
  "パラシェルターソレーラ": "Sorella Brella.png",
  "キャンピングシェルター": "Tenta Brella.png",
  "キャンピングシェルターソレーラ": "Tenta Sorella Brella.png",
  "キャンピングシェルターCREM": "Tenta Brella CRE-M.png",
  "スパイガジェット": "Undercover Brella.png",
  "スパイガジェットソレーラ": "Undercover Sorella Brella.png",
  "スパイガジェット繚": "Patternz Undercover Brella.png",
  "24式張替傘・甲": "Recycled Brella 24 Mk I.png",
  "24式張替傘・乙": "Recycled Brella 24 Mk II.png",

  "トライストリンガー": "Tri-Stringer.png",
  "トライストリンガーコラボ": "Inkline Tri-Stringer.png",
  "トライストリンガー燈": "Bulbz Tri-Stringer.png",
  "LACT-450": "REEF-LUX 450.png",
  "LACT-450デコ": "REEF-LUX 450 Deco.png",
  "LACT-450MILK": "REEF-LUX 450 MIL-K.png",
  "フルイドV": "Wellstring V.png",
  "フルイドVカスタム": "Custom Wellstring V.png",

  "ジムワイパー": "Splatana Stamper.png",
  "ジムワイパー・ヒュー": "Splatana Stamper Nouveau.png",
  "ジムワイパー封": "Stickerz Splatana Stamper.png",
  "ドライブワイパー": "Splatana Wiper.png",
  "ドライブワイパーデコ": "Splatana Wiper Deco.png",
  "ドライブワイパーRUST": "Splatana Wiper RUS-T.png",
  "デンタルワイパーミント": "Mint Decavitator.png",
  "デンタルワイパースミ": "Charcoal Decavitator.png"
});
